# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [1]:
import numpy as np

In [11]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """
    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    print('s=',s)
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    print('Z(np.sum(s))=',Z)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [12]:

np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = np.random.randn(5,5,3)
W = np.random.randn(5,5,3)
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)


s= [[[-3.28475317  0.18732227 -0.43731282]
  [-0.24688443  0.65945029  0.51169682]
  [-0.35028504 -0.14201182  0.13082251]
  [-0.04945008  0.17400349  1.38165868]
  [-0.12173306 -0.04678599  1.28057434]]

 [[-1.31867931 -0.03192619  0.32944705]
  [-0.0269632   0.24681895 -0.08512196]
  [-0.39361746  0.03930652 -0.31154691]
  [ 0.62882631  0.30571426 -0.15048003]
  [-0.37757515 -0.15901261 -0.58069248]]

 [[-0.11715518 -0.29381838  0.65535702]
  [ 0.22500938 -0.02189239  0.01738998]
  [-0.35213085  0.19835334 -1.42662643]
  [ 0.2601206   0.25174261  0.03434725]
  [ 1.20723772  1.89794856  0.02077532]]

 [[ 0.01568089 -0.14799036  2.67521243]
  [ 0.23636489 -1.14675218  0.37105975]
  [-0.57333973 -0.38618451  0.41895556]
  [-0.18034786 -0.10613204 -0.50667939]
  [-1.14530969  0.15722653  0.70174599]]

 [[ 0.4703903   0.65221352 -0.58696682]
  [-0.23902903  0.02274897  0.0140994 ]
  [-0.11513862  1.32054779  1.64008122]
  [-0.73939639 -0.19885622 -0.0392581 ]
  [ 0.09896376  0.20370451  0

In [3]:
print(np.random.randn(3,3))

[[ 1.20220722  0.4802877  -1.44692267]
 [ 0.84889471 -1.20444031 -1.23153316]
 [ 0.77877572  0.1006364  -0.09203756]]
